<!DOCTYPE html>
<html>
<head>
  <title><?php echo $title;?></title>
  <meta charset="UTF-8">
  <?php echo $csss; ?>
  <link rel="shortcut icon" href="<?php echo $constants['static_url']; ?>favicon.ico">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript">
    var BASE_URL = '<?php echo $constants['base_url'];?>';
    var STATIC_URL  = '<?php echo $constants['static_url'];?>';
    var CSRF = "<?php echo $constants['csrf']['secret']; ?>";
    var CSRF_KEY = '<?php echo $constants['csrf']['key']; ?>';
  </script>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="<?php echo $constants['base_url']; ?>">Utilitario JPs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<?php echo $constants['base_url']; ?>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Chat</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $logout_url;?>">Salir</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
      </form>
    </div>
  </nav>
</header>
<div id="workspace">