<form class="form-signin" action="/login/sign_up" method="post">
  <h1 class="h3 mb-3 font-weight-normal">Cambiar Contraseña</h1>
  <input type="hidden" name="key" value="value">
  <span class="extraData"></span>
  <!--EMAIL -->
  <label for="email" class="sr-only">Correo</label>
  <input type="email" id="email" class="form-control" placeholder="Correo" required="" autofocus="" name="email">
  <!--CSRF -->
  <input type="hidden" name="<?php echo $constants['csrf']['key']; ?>" value="<?php echo $constants['csrf']['secret']; ?>">
  <!--MESSAGE-->
  <p class="<?php echo $message_color; ?> message" style="margin-top:10px;" id="login-message"><?php echo $message; ?></p>
  <!--BUTTON -->
  <button class="btn btn-lg btn-primary btn-block" type="submit" style="margin-bottom: 10px;" onclick="return runError()">
    Enviar Correo
  </button>
  <!--FooTER LOGIN NAV -->
  <div class="link-login">
    <a class="" href="/login">
      Ingresar
    </a>
    <a id="forgotpassword" class="pull-right" href="/login/sign_up">
      Registrarse
    </a>
  </div>
  <p class="mt-5 mb-3 text-muted">Powered By <a href="http://softweb.pe/"> Softtware Web Perú</a> © 2017-2018</p>
</form>

<script type="text/javascript">
  function runError(){
    alert('Función aún no implementada');
    return false;
  }
</script>