<div class="row text-center">
  <h1 class="align-text-bottom"><?php echo $error['numero']; ?></h1>
</div>
<div class="row text-center">
	<div class="error-divider">
		<h2><?php echo $error['mensaje']; ?></h2>
		<p class="description"><?php echo $error['descripcion']; ?></p>
	</div>
	<a href="<?php echo $constants['base_url']; ?>login" class="return-btn"><i class="fa fa-home"></i>Ir al Inicio</a>
</div>
