<?php //var_dump($_SESSION); ?>
<div class="row">
  <div class="col-md-12">
    <h4 style="margin-bottom:15px">Detalles de las Secciones</h4>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <div class="form-group">
      <label for="sections">Secciones</label>
      <select class="form-control" id="sections" onchange="changeSection(this.value)">
        <option value="E"></option>
        <?php foreach ($sections as $section): ?>
        <option value="<?php echo $section['section_id']; ?>">
          <?php echo $section['section_code'] . ' - ' . $section['course_name']; ?>
        </option>
        <?php endforeach ?>
      </select>
    </div>
  </div>
  <div class="col-md-9">
    <div class="alert" id="message"></div>
    <div id="table"></div>
  </div>
</div>

<script type="text/javascript">
  function changeSection(section_id){
    if(section_id == 'E'){
      // none
    }else{
      $.ajax({
        type: 'GET',
        url: BASE_URL + 'section/get_students',
        data: {
          section_id: section_id,
        },
        headers: {
          [CSRF_KEY]: CSRF,
        },
        async: false,
        success: function(data){
          var students = JSON.parse(data);
          $('#table').empty();
          // create table
          var table = document.createElement('TABLE');
          table.classList.add('table');
          table.classList.add('table-striped');
          // thead
          var thead = document.createElement('THEAD');
          var rhead = document.createElement('TR');
          var th1 = document.createElement('TH');
          th1.innerHTML = 'Código';
          thead.appendChild(th1);
          var th2 = document.createElement('TH');
          th2.innerHTML = 'Alumno';
          thead.appendChild(th2);
          var th3 = document.createElement('TH');
          th3.innerHTML = 'TW Id';
          thead.appendChild(th3);
          var th4 = document.createElement('TH');
          th4.innerHTML = 'TW Password';
          thead.appendChild(th4);
          var th5 = document.createElement('TH');
          th5.innerHTML = 'Puntajes';
          thead.appendChild(th5);
          table.appendChild(thead);
          // append thead
          document.getElementById('table').appendChild(table);
          // tobdy
          var tbody = document.createElement('TBODY');
          for(var i = 0; i < students.length; i++){
            var tr = document.createElement('TR');
            // code
            var td1 = document.createElement('TD');
            td1.innerHTML = students[i].code;
            tr.appendChild(td1);
            // name
            var td2 = document.createElement('TD');
            td2.innerHTML = students[i].name;
            tr.appendChild(td2);
            // tw_id
            var td3 = document.createElement('TD');
            td3.innerHTML = students[i].tw_id;
            tr.appendChild(td3);
            // tw_pass
            var td4 = document.createElement('TD');
            td4.innerHTML = students[i].tw_pass;
            tr.appendChild(td4);
            // points
            var td5 = document.createElement('TD');
            var iAdd = document.createElement('i');
            iAdd.classList.add('fa');
            iAdd.classList.add('fa-plus');
            iAdd.classList.add('button-points');
            iAdd.setAttribute('aria-hidden', 'true');
            iAdd.setAttribute('operation', 'add');
            iAdd.setAttribute('section_id', students[i].section_id);
            iAdd.setAttribute('student_id', students[i].student_id);
            iAdd.setAttribute('onclick', 'studenPoints(event)');
            var spanPoint = document.createElement('span');
            if(students[i].points == null){
              spanPoint.innerHTML = 0;
            }else{
              spanPoint.innerHTML = students[i].points;
            }
            var iRemove = document.createElement('i');
            iRemove.classList.add('fa');
            iRemove.classList.add('fa-minus');
            iRemove.classList.add('button-points');
            iRemove.setAttribute('aria-hidden', 'true'); 
            iRemove.setAttribute('operation', 'remove');
            iRemove.setAttribute('student_id', students[i].student_id);
            iRemove.setAttribute('section_id', students[i].section_id);
            iRemove.setAttribute('onclick', 'studenPoints(event)');
            td5.appendChild(iRemove);
            td5.appendChild(spanPoint);
            td5.appendChild(iAdd);
            tr.appendChild(td5);
            // append tr
            tbody.appendChild(tr);
          }
          // append tbody
          table.appendChild(tbody);
        },
        error: function(xhr, status, error){
          console.error(error);
          $('#message').removeClass('text-warning');
				  $('#message').removeClass('text-success');
          $('#message').addClass('text-danger');
          $('#message').html('Ocurrió un error en actualizar la información de conexión de Teamviewer');
        }
      });
    }
  }
  // 
  function studenPoints(event){
    $.ajax({
        type: 'POST',
        url: BASE_URL + 'section/update_student_points',
        data: {
          section_id: event.target.getAttribute('section_id'),
          student_id: event.target.getAttribute('student_id'),
          operation: event.target.getAttribute('operation'),
        },
        headers: {
          [CSRF_KEY]: CSRF,
        },
        async: false,
        success: function(data){
          var span = event.target.parentElement.children[1];
          span.innerHTML = parseInt(data);
        },
        error: function(xhr, status, error){
          console.error(error);
          $('#message').removeClass('text-warning');
				  $('#message').removeClass('text-success');
          $('#message').addClass('text-danger');
          $('#message').html('Ocurrió un error en modificar el puntaje del alumno');
        }
      });
  }
</script>